language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
addons:
  apt:
    packages:
    - python-pypy.translator.sandbox
install:
    - travis_retry pip install -vr https://raw.githubusercontent.com/ProgVal/Limnoria/testing/requirements.txt > /dev/null
    - travis_retry pip install -v git+https://github.com/ProgVal/Limnoria.git@testing > /dev/null
    - travis_retry pip install -vr requirements.txt > /dev/null | true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - export PYTHON_MAJOR_VERSION=$(python -c "import sys;print(sys.version_info[0])")
  - echo $PYTHON_MAJOR_VERSION
  - if [ "$PYTHON_MAJOR_VERSION" = "3" ]; then export DISABLED_PLUGINS="--exclude ./Twitter --exclude ./TwitterStream --exclude ./MegaHAL --exclude GUI --exclude WebStats"; else export DISABLED_PLUGINS="--exclude Bitoduc --exclude PypySandbox"; fi
  - supybot-test --plugins-dir=. --no-network --exclude=./NoLatin1 --exclude ./AlternativeTo $DISABLED_PLUGINS
notifications:
    email: false
matrix:
    fast_finish: true
