[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-stocks"
version = "0.0.0"
authors = [

]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Stocks = "limnoria_stocks"

[tool.setuptools.package-dir]
"limnoria_stocks" = "."
"limnoria_stocks.local" = "local/"

[tool.setuptools.package-data]
"limnoria_stocks" = ["locales/*.po"]
