[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-trigger"
version = "0.1"
authors = [
    { name = "Valentin Lorentz" },
]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Trigger = "limnoria_trigger"

[tool.setuptools.package-dir]
"limnoria_trigger" = "."
"limnoria_trigger.local" = "local/"

[tool.setuptools.package-data]
"limnoria_trigger" = ["locales/*.po"]
