[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-wunderweather"
version = "%%VERSION%%"
authors = [
    { name = "James Vega" },
]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
WunderWeather = "limnoria_wunderweather"

[tool.setuptools.package-dir]
"limnoria_wunderweather" = "."
"limnoria_wunderweather.local" = "local/"

[tool.setuptools.package-data]
"limnoria_wunderweather" = ["locales/*.po"]
