[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-sudo"
version = "0.1"
authors = [
    { name = "Valentin Lorentz" },
]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Sudo = "limnoria_sudo"

[tool.setuptools.package-dir]
"limnoria_sudo" = "."
"limnoria_sudo.local" = "local/"

[tool.setuptools.package-data]
"limnoria_sudo" = ["locales/*.po"]
