[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-wikipedia"
version = "0.1"
authors = [
    { name = "quantumlemur" },
    { name = "Valentin Lorentz" },
]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Wikipedia = "limnoria_wikipedia"

[tool.setuptools.package-dir]
"limnoria_wikipedia" = "."
"limnoria_wikipedia.local" = "local/"

[tool.setuptools.package-data]
"limnoria_wikipedia" = ["locales/*.po"]
